VIRTIO_CONFIG_STATUS_RESET = 0x00
VIRTIO_CONFIG_STATUS_ACK = 0x01
VIRTIO_CONFIG_STATUS_DRIVER = 0x02
VIRTIO_CONFIG_STATUS_DRIVER_OK = 0x04
VIRTIO_CONFIG_STATUS_FEATURES_OK = 0x08
VIRTIO_CONFIG_STATUS_FAILED = 0x80

VIRTIO_PCI_HOST_FEATURES = 0
VIRTIO_PCI_GUEST_FEATURES = 4
VIRTIO_PCI_QUEUE_PFN = 8
VIRTIO_PCI_QUEUE_NUM = 12
VIRTIO_PCI_QUEUE_SEL = 14
VIRTIO_PCI_QUEUE_NOTIFY = 16
VIRTIO_PCI_STATUS = 18

VIRTIO_NET_F_CSUM = 0
VIRTIO_NET_F_GUEST_CSUM = 1
VIRTIO_NET_F_MTU = 3
VIRTIO_NET_F_MAC = 5
VIRTIO_NET_F_GUEST_TSO4 = 7
VIRTIO_NET_F_GUEST_TSO6 = 8
VIRTIO_NET_F_GUEST_ECN = 9
VIRTIO_NET_F_GUEST_UFO = 10
VIRTIO_NET_F_HOST_TSO4 = 11
VIRTIO_NET_F_HOST_TSO6 = 12
VIRTIO_NET_F_HOST_ECN = 13
VIRTIO_NET_F_HOST_UFO = 14
VIRTIO_NET_F_MRG_RXBUF = 15
VIRTIO_NET_F_STATUS = 16
VIRTIO_NET_F_CTRL_VQ = 17
VIRTIO_NET_F_CTRL_RX = 18
VIRTIO_NET_F_CTRL_VLAN = 19
VIRTIO_NET_F_CTRL_RX_EXTRA = 20
VIRTIO_NET_F_GUEST_ANNOUNCE = 21
VIRTIO_NET_F_MQ = 22
VIRTIO_NET_F_CTRL_MAC_ADDR = 23
VIRTIO_F_NOTIFY_ON_EMPTY = 24
VIRTIO_F_ANY_LAYOUT = 27
VIRTIO_RING_F_INDIRECT_DESC = 28
VIRTIO_F_VERSION_1 = 32
VIRTIO_F_IOMMU_PLATFORM = 33

VIRTIO_PCI_QUEUE_ADDR_SHIFT = 12

VRING_AVAIL_F_NO_INTERRUPT = 1

# This marks a buffer as continuing via the next field. */
VRING_DESC_F_NEXT = 1
# This marks a buffer as write-only (otherwise read-only). */
VRING_DESC_F_WRITE = 2
# This means the buffer contains a list of buffer descriptors. */
VRING_DESC_F_INDIRECT = 4

"""
 Control the RX mode, ie. promiscuous, allmulti, etc...
 All commands require an "out" sg entry containing a 1 byte
 state value, zero = disable, non-zero = enable.  Commands
 0 and 1 are supported with the VIRTIO_NET_F_CTRL_RX feature.
 Commands 2-5 are added with VIRTIO_NET_F_CTRL_RX_EXTRA.
 """
VIRTIO_NET_CTRL_RX = 0
VIRTIO_NET_CTRL_RX_PROMISC = 0
VIRTIO_NET_CTRL_RX_ALLMULTI = 1
VIRTIO_NET_CTRL_RX_ALLUNI = 2
VIRTIO_NET_CTRL_RX_NOMULTI = 3
VIRTIO_NET_CTRL_RX_NOUNI = 4
VIRTIO_NET_CTRL_RX_NOBCAST = 5
